apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-production","spec.ingressClassName":"nginx"},"labels":{"name":"myingress"},"name":"myingress","namespace":"default"},"spec":{"rules":[{"host":"blog.bestofcreativity.online","http":{"paths":[{"backend":{"service":{"name":"bloggin-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}},{"host":"php.bestofcreativity.online","http":{"paths":[{"backend":{"service":{"name":"phpmyadmin-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["blog.bestofcreativity.online","php.bestofcreativity.online"],"secretName":"myapp-tls"}]}}
    spec.ingressClassName: nginx
  creationTimestamp: "2024-07-05T17:17:01Z"
  generation: 1
  labels:
    name: myingress
  name: myingress
  namespace: default
  resourceVersion: "3626"
  uid: 40856af4-e498-40a8-bdb2-456eb23c1b63
spec:
  rules:
  - host: blog.bestofcreativity.online
    http:
      paths:
      - backend:
          service:
            name: bloggin-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: php.bestofcreativity.online
    http:
      paths:
      - backend:
          service:
            name: phpmyadmin-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - blog.bestofcreativity.online
    - php.bestofcreativity.online 
    secretName: myapp-tls
status:
  loadBalancer: {}
