apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: myapp
    meta.helm.sh/release-namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: elishabassey2222@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

